### ISSUE TITLE
Push Button Module

### ISSUE THREAD

**Issue by thefurfel** [RaspberryWallet/Backend#1]
**Prerequisites:**
* uses private key generated during first installation
* uses GPIO - pi4j
* timeout watchdog would be a good idea

**Testing:**
* GPIO can be mocked during testing
* private key can be generated before test and remain the same

How it works:
```
encrypt(data):
return AES.encrypt(PublicKey, data);
end

register():
end

check():
return GPIO.checkButton()
end

decrypt():
return AES.decrypt(PrivateKey, data);
end
```

**Comment by stanbar** [comment]
What kind of `data` can hold button ?

**Comment by thefurfel** [comment]
https://github.com/RaspberryWallet/Backend/wiki/How-Modules-work

**Comment by PatrykMilewski** [comment]
@pfoof @stasbar I see this in code, but is this fully implemented?

**Comment by PatrykMilewski** [comment]
@pfoof can you finish it today?

It's funny, that it's #1 issue :1st_place_medal:

**Comment by PatrykMilewski** [comment]
Weekly reminder to finish this branch @pfoof :hourglass_flowing_sand:

**Comment by PatrykMilewski** [comment]
Does it even make sense to keep this branch, since there are like one thousand conflicts with current master?

@pfoof @stasbar

**Comment by stanbar** [comment]
I have no idea why is this issue/branch still open.

**Comment by PatrykMilewski** [comment]
Is Push Button module fully implemented? I think, it is not
https://github.com/RaspberryWallet/Backend/blob/master/Manager/src/main/java/io/raspberrywallet/manager/modules/pushbutton/PushButtonModule.java

**Comment by stanbar** [comment]
I think it is. Button cannot hold any cipher, so it can just return the data. Or we can pass it throught NOT function

**Comment by stanbar** [comment]
And we must test it in practice. @pfoof

**Comment by PatrykMilewski** [comment]
It should test if GPIO is in correct state and then return data, if it is not then throw exception, i would do it as simple as that

saving static encryption key to file would give us nothing imo

**Comment by PatrykMilewski** [comment]
Push Button module was implemented in other branches. Closing
