### ISSUE TITLE
Module class missing destroy method and we need this

### ISSUE THREAD

**Issue by PatrykMilewski** [RaspberryWallet/Backend#105]
By design, all of our modules are stateless and because of that, there is no sense in making destroy method.

There is problem with PINModule, that it is not stateless by design of Pi4J library.

When you set listener on GPIO pin, then it is "occupied" until you release it with method call from Pi4J. If pin is occupied and you are trying to occupy it once again, then Exception is thrown.
This situation will occur, when wallet is reinitialized after locking. PushButton module won't release his GPIO and a new instance of PushButton module will try to lock it. 

I haven't tested it, beacause I can't get to work my RPI right now, but I'm almost sure, that it will occure.

So we have to implement destroy merhod in Module class:
```
public void destroy() {
     return;
}
```

It will be overwritten, if module actually needs to. By default it's just dummy method.

destroy should be called after locking Wallet in Manager class

I will confirm this tommorow, after I get back my mini HDMI adapter from @stasbar

**Comment by stanbar** [comment]
unlockWallet() does not initialize the modules it just call `encryptKeyPart()`

Each `Module` is initialized only once during Manager `main()` method.
