### ISSUE TITLE
PIN Module

### ISSUE THREAD

**Issue by thefurfel** [RaspberryWallet/Backend#13]
```
String pin = null;
encrypt(data):
return AES.encrypt(PublicKey, data);
end

register():
pin = null;
setStatus("Enter PIN code. <form:pin>");
end

check():
return pin != null && pin.length > 3
end

decrypt():
return AES.decrypt( PrivateKey(pin), data );
end
```
What's more, frontend should react on `<form:pin>` and show the form, which will post data to Module.
Needs extending Module.java to hold and be able to handle dynamic input: `HashMap<String, String>`

**Comment by PatrykMilewski** [comment]
What about entering PIN with physical keyboard on RPI? Are we going to do this only by web panel?

**Comment by thefurfel** [comment]
@PatrykMilewski that would be a different module

**Comment by PatrykMilewski** [comment]
> @PatrykMilewski that would be a different module

ok, you are right

**Comment by PatrykMilewski** [comment]
@pfoof @stasbar  I see this in code, but is this fully implemented?

**Comment by stanbar** [comment]
Yes, but I used xor instead of aes :D

**Comment by PatrykMilewski** [comment]
Okay, then please make a new issue nad assign me, i will drive it to the
end :D

pt., 26 paź 2018, 15:38 użytkownik Stanislaw Baranski <
notifications@github.com> napisał:
