### ISSUE TITLE
Refactor of imported module, that is implementing Objects and Streams encryption

### ISSUE THREAD

**Issue by PatrykMilewski** [RaspberryWallet/Backend#17]
Since this module:
https://github.com/RaspberryWallet/Backend/tree/master/Manager/src/main/java/io/raspberrywallet/manager/cryptography/crypto

is imported from other project, it needs some refactor. There is no single entry point and I want to make this way. It would be easier for you to use that.

**Comment by stanbar** [comment]
Ok, good luck.

**Comment by PatrykMilewski** [comment]
Done
