### ISSUE TITLE
RPI Performance

### ISSUE THREAD

**Issue by stanbar** [RaspberryWallet/Backend#29]
We need to find the best software stack that will handle our requirements.
**OS**: We should try both Rasbian and DietPi. It may turn out that Raspbian is more stable and so faster.
**JDK**: According to https://raspberrypi.stackexchange.com/a/43912 We should use Oracle JDK
**ServerFramework**: We should try VertX, Ktor(Netty) and Ktor(Jetty) and find which perform best.

**Comment by pfoof** [comment]
**OS**: https://docs.google.com/spreadsheets/d/1mDHGZC-H6tU6_O8kuLTG8d4A8Nt7lV1Q7MXTR_6qw30/edit#gid=0 (even though from 2015 and DietPi keeps in line with Raspian therefore 99% of the system is the same, only config varies)
**JDK**: benchmarking both, will post results later

**Comment by pfoof** [comment]
Benchmark results:
https://docs.google.com/spreadsheets/d/1a1OVP222QlkPdzlxxynXhlwhVE-9O08XIMxoJKJLtJc/edit?usp=sharing

**Comment by stanbar** [comment]
Nice. So indeed, Oracle is slightly better.

**Comment by pfoof** [comment]
`sudo ln -s /usr/lib/jvm/jdk1.8.0_181/bin/java /etc/alternatives/java`

**Comment by stanbar** [comment]
Sorry @pfoof didn't get the joke :(

**Comment by pfoof** [comment]
It's not a joke, it's a command to pin a different version of java

**Comment by PatrykMilewski** [comment]
So indeed, we stay with Oracle and DietPi?

**Comment by PatrykMilewski** [comment]
> So indeed, we stay with Oracle and DietPi?

meeting: yup
