### ISSUE TITLE
How to send data from backend to frontend?

### ISSUE THREAD

**Issue by PatrykMilewski** [RaspberryWallet/Backend#42]
1. Set high timeout and send get data request from frontend to backend.
2. When backend has data, it is responding to this request.
3. If there is still no data on backend, then there is timeout and we can go back to 1.

**Comment by stanbar** [comment]
I will do that

**Comment by stanbar** [comment]
I think that websockets will be good approach

**Comment by PatrykMilewski** [comment]
@stasbar could you paste link to a branch, when you start? I would like to take a look, how it works

**Comment by PatrykMilewski** [comment]
Shouldn't it change to nice to have features? If it's hard to implement, we may look for easier solution and implement this after first release

**Comment by stanbar** [comment]
That's a good idea. But I will take it whenever we finish all main features
