### ISSUE TITLE
Configure wireless network

### ISSUE THREAD

**Issue by pfoof** [RaspberryWallet/Backend#43]
- [x] show current saved network
- [x] receive and save password for wpa-supplicant
- [x] select network to connect
- [x] fix dhcp client to add ip route (still looking for solutions)
- [x] show list of scanned networks (periodically)

https://www.linuxbabe.com/command-line/ubuntu-server-16-04-wifi-wpa-supplicant

**Comment by stanbar** [comment]
What kind of interface would you like to connect it to ? SSH or Frontend ?

**Comment by pfoof** [comment]
SSH will be disabled when we finish the project.

**Comment by stanbar** [comment]
Ok, I get it. So it will be a web interface to configure WiFi thought USB Ethernet ?

**Comment by pfoof** [comment]
Yeah, already started implementing configuration editor in backend

**Comment by pfoof** [comment]
Finished, added refresh button, route is saved and reloaded after reboot.
