### ISSUE TITLE
ClassLoader load signed .jar's

### ISSUE THREAD

**Issue by stanbar** [RaspberryWallet/Backend#44]
Refactor ClassLoader to load signed .jar's instead of raw byecode 

https://stackoverflow.com/questions/34641305/is-it-possible-to-force-jvm-to-check-that-every-jar-must-be-signed

https://docs.oracle.com/javase/tutorial/security/toolsign/index.html

**Comment by pfoof** [comment]
Also: remove option "modules directory" from manager.cli. Let's assume it's /opt/wallet/modules/
