### ISSUE TITLE
Auto locking manager 

### ISSUE THREAD

**Issue by stanbar** [RaspberryWallet/Backend#47]
I suggest to implement auto locking mechanism, that will lock the device, after some period of time ( (default: 10min ?)

It would be as easy as
```java
class Manager{

    private int autoLockRemainingMinutes = 10;

    Manager(){
        Timer timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                if (autoLockRemainingMinutes == 1) {
                    lockWallet();
                    timer.cancel();
                }
                --autoLockRemainingMinutes;

            }
        }, 60000, 60000);
    }
    
    void tap(){
        autoLockRemainingMinutes = 10;
    }
}
```

**Comment by stanbar** [comment]
This must be improved (UI timer) and tested

**Comment by stanbar** [comment]
It's working fine in practise

**Comment by PatrykMilewski** [comment]
Is it implemented already? Or in #70 ?

**Comment by stanbar** [comment]
It's implemented in 50%, because It's working in backend, but there is no frontend view, like timer or just TextView to display time remaning. I will implement it with WebSockets

**Comment by PatrykMilewski** [comment]
Checking state, @stasbar how it looks right now? Same as 10 days ago?
