### ISSUE TITLE
Encrypted Database for keyparts

### ISSUE THREAD

**Issue by PatrykMilewski** [RaspberryWallet/Backend#52]
This will be blocker, it's important to implement this. Any ideas which database we should use?

Task for @pfoof

**Comment by stanbar** [comment]
As far as i remember, we decided to use just aes-encrypted file serialized with JSON

**Comment by PatrykMilewski** [comment]
Okay, then we have to make logic for it

pt., 26 paź 2018, 15:40 użytkownik Stanislaw Baranski <
notifications@github.com> napisał:

**Comment by PatrykMilewski** [comment]
@stasbar are we going to use Java built-in serialization, or you want to use something else?

**Comment by pfoof** [comment]
@PatrykMilewski we already have serialization using jackson. `io.raspberrywallet.manager.database.Database` keeps a `WalletEntity` which holds an array of `KeyPartEntity`.

**Comment by PatrykMilewski** [comment]
@PatrykMilewski will implement AES encyrption in Database class

**Comment by PatrykMilewski** [comment]
@pfoof please take a look on branch: c4f1fe6bfef5ebb339a6efb07fefbbd66e179b9c

I need some logic verification, if it's going the right way

**Comment by stanbar** [comment]
Since keyparts are native encrypted, do we need to encrypt the database ?
By native, I mean that keypart is never ever saved in raw/decrypted form. 
It might bring some complexity, like a password to encrypt database file.

**Comment by pfoof** [comment]
Structure of the database should also be protected.

**Comment by PatrykMilewski** [comment]
Adding something to what @pfoof said, it's good idea to encrypt whole database, since some modules might encrypt keypart in naive way, like xor operation or something, they still may be protected when somebody might try to attack wallet

**Comment by stanbar** [comment]
You are right, let's encrypt it as well
