### ISSUE TITLE
SecureRandom alternative

### ISSUE THREAD

**Issue by PatrykMilewski** [RaspberryWallet/Backend#53]
Since SecureRandom not works for RPI, we have to find alternative.

@stasbar @pfoof  You guys were saying something about hardware random generator in RPI. Could you please move the information here?

**Comment by stanbar** [comment]
Ryszard suggested to use https://www.nico-maas.de/?p=1562 and it indeed works :)

**Comment by PatrykMilewski** [comment]
Then can @pfoof implement it? Would be nice to replace all random
generators with it

pt., 26 paź 2018, 15:42 użytkownik Stanislaw Baranski <
notifications@github.com> napisał:

**Comment by pfoof** [comment]
Installed, should work out of the box with previous `SecureRandom`

**Comment by PatrykMilewski** [comment]
okay, then let's change this in code
