### ISSUE TITLE
Application specific files location

### ISSUE THREAD

**Issue by PatrykMilewski** [RaspberryWallet/Backend#59]
Database is encrypted then serialized and saved to file as byte array in file database.bin

Default path is `./database.bin` which probably project root path, or something like that.

I suggest to move it to /opt/wallet, but this change needs discussion, since it's important, where we store most important data.

@pfoof @stasbar

**Comment by stanbar** [comment]
I think that it's must have change, because I can't imagine the situation where the cwd execution  decide where the database is saved. 
I will do the same with blockchain(`.spvchain`) and `.wallet` files. They will be saved into `/opt/wallet/bitcoinj`

**Comment by stanbar** [comment]
Then we can allow each module to have access to it's own`/opt/wallet/custom_module/` directory

**Comment by PatrykMilewski** [comment]
Okay, then database is going to /opt/wallet/database.bin

Please confirm

**Comment by stanbar** [comment]
Confirmed 😄

**Comment by pfoof** [comment]
The application is executed in /opt/wallet which is the `~` directory for its user.

**Comment by stanbar** [comment]
@pfoof Well, that changes a lot.
So, should the base directory be defined by enviroment variable $HOME or in config.yaml file ? 
Or maybe $HOME will be default, and config.yaml will be able to overwrite it ?
@pfoof @PatrykMilewski

**Comment by PatrykMilewski** [comment]
I think that we should stay with full paths, because a lot of code is implemented like this.

**Comment by PatrykMilewski** [comment]
Can we make a decision and close this issue? The original question was already answered and implemented.

**Comment by PatrykMilewski** [comment]
Keep with full paths
