### ISSUE TITLE
Test authentication server in practise 

### ISSUE THREAD

**Issue by stanbar** [RaspberryWallet/Backend#71]
We need to test authentication server in practise, full use case with webapp.

**Comment by PatrykMilewski** [comment]
There are junit tests, that test the whole logic, aren't they enough? Server have to be online to make it work

**Comment by stanbar** [comment]
Could you please deploy this container on heroku ? It will work with free plan.

**Comment by PatrykMilewski** [comment]
Okay I will look into this tommorow

**Comment by stanbar** [comment]
Ok, and @pfoof could you please make simple register form in `kotlinx.html` like you did for wifi configuration ?

**Comment by PatrykMilewski** [comment]
> Ok, and @pfoof could you please make simple register form in kotlinx.html like you did for wifi configuration ?

As we said on Messenger, there is no need of implementing that, since this module does register by itself

Since it is not really Backend job to do it, this Issue will be resolved there:
https://github.com/RaspberryWallet/AuthorizationServer/issues/8
