### ISSUE TITLE
Displaying wallet operations history

### ISSUE THREAD

**Issue by stanbar** [RaspberryWallet/Backend#76]
Implement operations history

**Comment by PatrykMilewski** [comment]
Can we discuss about how it will be stored? Storing logs in JSON is the best approach atm in my opinion. Reading them with other tools like elasticsearch, would be then really easier (not saying that we are going to do this, just our users)

**Comment by PatrykMilewski** [comment]
Also we may think about adding a layer of abstraction to logging in overall. Then if we would like to improve our logging system, then it would be a lot easier to modify our custom logging interface

**Comment by stanbar** [comment]
It's already implemented in BitcoinJ. Those operations are stored and encrypted in `.wallet` file.

**Comment by PatrykMilewski** [comment]
@stasbar So basically operations history is stored in file, but theere is no frontend logic to show it?

If yes, then this Issue should be renamed to "Displaying wallet operations history" instead, or something like that

**Comment by stanbar** [comment]
Right
