### ISSUE TITLE
Use of Kotlin in Manager module

### ISSUE THREAD

**Issue by PatrykMilewski** [RaspberryWallet/Backend#8]
Are we going to use Kotlin language in Manager module?

There was thoughts about it long ago, but today I think, that it should be avoided, to provide the cleaner code, since multiple languages will cause a lot of chaos.

This question is mainly addressed to @stasbar

**Comment by stanbar** [comment]
Sure, we decided that Manager will be pure java

**Comment by PatrykMilewski** [comment]
Okay, then I need to make a change in maven pom file, since there are some changes in it for Kotlin
