### ISSUE TITLE
Random string generator

### ISSUE THREAD

**Issue by PatrykMilewski** [RaspberryWallet/Backend#81]
When I was debugging something, I've found that my random string generator was not really that random:
```
byte[] randomBytes = new byte[PASSWORD_SIZE_IN_BYTES];
random.nextBytes(randomBytes);
return new String(randomBytes, Charset.forName("UTF-8"));
```
I've found it in Google and I've been using it for some time. The problem is, that `random.nextBytes` may generate negative numbers, which will be converted to character with code 65533. In a result, half of a random string is going to be 65533 chars, since getting a nagative character is around 50% chance. 

A lot of google answers about "how to generate random string in java" is affected with this. For example:
https://www.baeldung.com/java-random-string

I will fix it on my actual feature branch (authserver-https). I'm writting this to just warn you, because you may used it like this somewhere else and without special test for this, it's really hard to find it.

**Comment by stanbar** [comment]
Good point !

**Comment by stanbar** [comment]
Isn't it simpler to just use Base64/58/32 encoding?

**Comment by PatrykMilewski** [comment]
Yes, it is simpler, I will change that in #84
