### ISSUE TITLE
First release - finish main features

### ISSUE THREAD

**Issue by PatrykMilewski** [RaspberryWallet/Backend#86]
We have to finish implementation phase. 

Let's list what we got left:
1. confirm that PINModule is finished (#1) @pfoof 
2. refactor Module interface (remove check, move reposibility to enc / dec)
3. test system on RPI @pfoof 

@pfoof @stasbar

**Comment by PatrykMilewski** [comment]
I think that we have to implement 2. due to problems with some modules, that currently may not work with / without check call

**Comment by stanbar** [comment]
We need to test everything in practice on rpiz @pfoof we don't even know if it will work.
By everything I mean, scenario when we use all modules to lock wallet, synchronize and send funds.

**Comment by PatrykMilewski** [comment]
> We need to test everything in practice on rpiz @pfoof we don't even know if it will work.
> By everything I mean, scenario when we use all modules to lock wallet, synchronize and send funds.

Yup but right now I'm 100% sure, that some of modules will not work due to 2.

**Comment by stanbar** [comment]
Ok, so who is willing to implement 2. ?

**Comment by PatrykMilewski** [comment]
I can, but somebody have to verify Modules Manager logic if it works correctly then

**Comment by PatrykMilewski** [comment]
Created #87 for 2.

**Comment by stanbar** [comment]
PR for 2. https://github.com/RaspberryWallet/Backend/pull/88

**Comment by PatrykMilewski** [comment]
We need tests 3. @pfoof

**Comment by PatrykMilewski** [comment]
Closing this issue, 3. will be continued in #98
