### ISSUE TITLE
Refactor of Module abstract class

### ISSUE THREAD

**Issue by PatrykMilewski** [RaspberryWallet/Backend#87]
Due to missunerstandings of official Module API provided in this class, there are some problems with current Modules implementations.

We have to refactor this class to work like this:
1. Set needed inputs.
2. Call enc / dec method
3a. If the requirements for this operations didn't meet, then exception is thrown and the error message is passed to user
3b. Method returns correct output.

What do you guys think? I think, that it should be as simple as possible.

@stasbar @pfoof

**Comment by PatrykMilewski** [comment]
Branch for this issue:
https://github.com/RaspberryWallet/Backend/tree/module-class-refactor

**Comment by stanbar** [comment]
Isn't it as simple as remove the `check()` and add input check to enc/dec ?
in ExampleModule, PinModule and PushButtonModule this method body is stateless, it just return if the input is set. We can move this checks to enc/dec and throw RequiredInputNotFound if it's not set.

**Comment by stanbar** [comment]
Of we can add validateInput() where the validation needs to be done and throw `RequiredInputNotFound` if its not present.

**Comment by stanbar** [comment]
Or not, it may bring unnecessary complexity

**Comment by stanbar** [comment]
But will make our framework consistent. And fore module implementations to validateInputs

**Comment by PatrykMilewski** [comment]
Edit: dropping this idea for validateInput

As you said first, remove check and do check work in enc dec, I started refactoring it already like this
